### ISSUE TITLE
[Mac] Impossible to launch Skizzle because the developer is not certified

### ISSUE THREAD

**Issue by franck-mahieu** [AxaGuilDEv/Skizzle#92]
Is it possible to certified the application  ? 

<img width="415" alt="Capture d’écran 2020-11-26 à 09 23 52" src="https://user-images.githubusercontent.com/9554454/100325547-1ad48780-2fc9-11eb-8be2-06d037a03f6e.png">

**Comment by itupix** [comment]
Sadly, it's not possible for now. We need an Apple developper account, we asked for it but still waiting. But the good news is you can use Skizzle on macOS without it, as explained here : https://github.com/AxaGuilDEv/Skizzle/wiki/FAQ

**Comment by franck-mahieu** [comment]
Oh right, thanks, it works well, sorry for the inconvenience, i don't read the FAQ !  thanks for the jobs
